version: '3'

services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  
  java:
    build: ./Java
    volumes:
      - ./Java:/data
    environment:
      ENV JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
    ports:
      - 8080:8080
      - 9990:9990